### ISSUE TITLE
fix lint CICD

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-nuxt-template#50]
im getting alot of PRs that FAIL.... but  could pass if we have it auto fix

Heres a couple ways i think we can solve

1. add the --write flag to the cicd
2. add a pre-commit hook file to the repo to always run prettier --write on commits
3. both

![image.png](https://volta.s3.fr-par.scw.cloud/image_6337fe9942.png)

@dawaltconley

**Comment by dawaltconley** [comment]
added formatting (writing to file) to precommit hooks in the `dev` branch
