### ISSUE TITLE
precommit hooks (faster)

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/serp-nuxt-template#69]
i set up precommit hooks that only run on staged files (not everything everytime) so its fast.

implementation here: https://github.com/serpcompany/serp-ui-nuxt

i say we do it.... @dawaltconley thoughts?

**Comment by dawaltconley** [comment]
I'm down, I don't see the implementation though, did you mean to link to Nuxt UI?

**Comment by devinschumacher** [comment]
@dawaltconley  maybe i hadnt commited it to main. take a look now. theres a .husky folder - https://github.com/serpcompany/serp-ui-nuxt/tree/main/.husky

**Comment by devinschumacher** [comment]
@dawaltconley i have since found what are apparently even faster precommit hooks than husky, but havent tried them out yet. just FYI

**Comment by dawaltconley** [comment]
@devinschumacher faster would be better, but we can figure that out later. added husky for now to the `dev` branch.
